---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: <%= ENV["machine_port"] %>
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: bento/centos-6.8


# I could not find an "official" vmware_fusion trusty box

# Adding auditd with cis ruleset addresses CIS CentOS Benchmark V1.0.0 4.2.2 and 4.2.4-18
# NOTE: 4.2.17 needs to be uncommented. and 4.2.12 needs to be confirmed. See cis template for more info.
# Note: There is probably a better way to pull in auditd and apply the cis attribute, this works for now.
suites:
  - name: default
    run_list:
      - recipe[auditd]
      - recipe[stig]
      - recipe[stig::auditd]
      - recipe[stig::auditd_rules]
    attributes: {
      "auditd" : {
        "ruleset" : "stig"
      }
    }
